# Generated by Django 3.2.10 on 2021-12-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamezz', models.CharField(max_length=90)),
                ('totals', models.IntegerField(default=0)),
                ('recordtotals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordid', models.IntegerField(default=None)),
                ('typezz', models.CharField(max_length=1)),
                ('values', models.IntegerField(default=0)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurnal.journal')),
            ],
        ),
    ]
